spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    #url: jdbc:postgresql://${DB_LINK}:${DB_PORT}/${DB_NAME}
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

application:
  security:
    jwt:
      secret: ${JWT_SECRET_KEY}
      access: ${ACCESS_TOKEN_EXPIRATION}
      refresh: ${REFRESH_TOKEN_EXPIRATION}

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /api/v1/swagger-ui
  api-docs:
    path: /api/v1/docs
